#! /bin/bash
# Writen by Niraj K. Nepal, Ph.D.
# Extract the total energies of scf converged calculations obtain from 'mainprogram 24'
# Runs for 'mainprogram 25'

file=$(find * -name $3 | tail -n 1)
echo "---------------------------------------------------------------------------------------------------------------"
echo "Extracting the total energies of structures corresponding to different mode"
echo "---------------------------------------------------------------------------------------------------------------"
for ((ii=$1; ii<$2; ++ii)); do
  A=$(grep "v$ii\ " $file | awk '{print $2}')
  B=$(grep "v$ii\ " $file | awk '{print $3}')
  echo "$A $B"
  if [[ ! -d R$A-$B ]]; then
    continue
  fi
  if [[ -f R$A-$B/relax/scf.in ]]; then
   nat=$(grep nat R$A-$B/relax/scf.in | awk '{print $3}')
   Nt=${nat%,*}
   nmode=$(echo $Nt*3+1 | bc)
  else
   echo "scf.in not present inside R$A-$B/relax"
   continue
  fi

  cd R$A-$B/
    touch Energy-mode.csv
    energy-distort-scan 1 $nmode
    rm *.dat
    rm *temp*
  cd ../
################
## SUBMIT JOB ##
################
done

