#! /bin/bash
# Writen by Niraj K. Nepal, Ph.D.
# Submit calculations for DOS processing
# Runs for 'mainprogram 17'
source jobscript.sh

file=$(find * -name $3 | tail -n 1)
echo "---------------------------------------------------------------------------------------------------------------"
echo "Calculations for DOS processing"
echo "---------------------------------------------------------------------------------------------------------------"
for ((ii=$1; ii<$2; ++ii)); do
  A=$(grep "v$ii\ " $file | awk '{print $2}')
  B=$(grep "v$ii\ " $file | awk '{print $3}')
  echo "$A $B"
  if [[ ! -d R$A-$B/dos ]] ; then
      mkdir R$A-$B/dos
  fi
   cp run-dosp.sh R$A-$B/dos/
    echo " submitting jobs in R$A-$B "
    cd R$A-$B/dos
       qerun "$A" "$B" "dosp"
       sleep 1s
    cd ../../
done
echo "all done"
