#! /bin/bash
# Writen by Niraj K. Nepal, Ph.D.
# submit calculations to diagonalize phonon dynamical matrices and create dynmat.axsf file.
# Runs for 'mainprogram 23'
source jobscript.sh

file=$(find * -name $3 | tail -n 1)
echo "---------------------------------------------------------------------------------------------------------------"
echo "Diagonalizing phonon dynamical matrices"
echo "---------------------------------------------------------------------------------------------------------------"
for ((ii=$1; ii<$2; ++ii)); do
  A=$(grep "v$ii\ " $file | awk '{print $2}')
  B=$(grep "v$ii\ " $file | awk '{print $3}')
  echo "$A $B"
  
  prefix=$(grep "prefix = " R$A-$B/relax/scf.in | awk '{print $3}' | sed 's/.$//')
  if [[ -d R$A-$B/calc ]]; then
    folder="calc"
  else
    folder="phonon"
  fi
  if [[ -f R$A-$B/$folder/$B.dyn1 ]] || [[ -f R$A-$B/$folder/$B.dyn ]] ; then
  
  q2r.py $A $B $prefix
  mv dynmat-$A-$B.in R$A-$B/$folder/dynmat.in
  cp run-dynmat.sh R$A-$B/$folder/
    echo " submitting jobs in R$A-$B "
    cd R$A-$B/$folder
       cp $B.dyn1 $B.dyn
       qerun "$A" "$B" "dynmat"
       sleep $SLEEP
    cd ../../
  else
     echo "electron-phonon calculation not finished"
  fi
done
echo "all done"
