#! /bin/bash
# Writen by Niraj K. Nepal, Ph.D.
# Submit calculation for partial DOS (PDOS)
# Runs for 'mainprogram 18'
source jobscript.sh

echo "---------------------------------------------------------------------------------------------------------------"
echo "Submitting partial DOS calculations"
echo "---------------------------------------------------------------------------------------------------------------"
file=$(find * -name $3 | tail -n 1)
for ((ii=$1; ii<$2; ++ii)); do
  A=$(grep "v$ii\ " $file | awk '{print $2}')
  B=$(grep "v$ii\ " $file | awk '{print $3}')
  echo "$A $B"
  if [[ ! -d R$A-$B/dos ]] ; then
      mkdir R$A-$B/dos
  fi
   cp run-pdos.sh R$A-$B/dos/
    echo " submitting jobs in R$A-$B "
    cd R$A-$B/dos
       qerun "$A" "$B" "pdos"
       sleep $SLEEP
    cd ../../
done
echo "all done"

