#! /bin/bash
# Writen by Niraj K. Nepal, Ph.D.
# Perform QE scf relaxation for different pressure.
# Runs for 'mainprogram 26'
source jobscript.sh

echo "---------------------------------------------------------------------------------------------------------------"
echo "Performing relaxation of systems under pressure"
echo "---------------------------------------------------------------------------------------------------------------"
file=$(find * -name $3 | tail -n 1)
dft=$(grep "DFT" input.in | awk '{ print $3 }')
for ((ii=$1; ii<$2; ++ii)); do
    A=$(grep "v$ii\ " $file | awk '{print $2}')
    B=$(grep "v$ii\ " $file | awk '{print $3}')
    echo "$A $B"
    if [[ ! -d R$A-$B/pressure ]] ; then
      echo " making R$A-$B/pressure directory "
      mkdir R$A-$B/pressure
    fi
    NP=$(wc -l pressure.in | awk '{print $1}')
    if [[ -f mpid-pressure-1.in ]] && [[ ! -f R$A-$B/pressure/mpid-pressure.in ]]; then
      grep "$B" mpid-pressure-1.in | grep "$A" > R$A-$B/pressure/mpid-pressure.in
    fi
    if [ $dft == 'vasp' ] || [ $dft == 'VASP' ] ; then
      #mainprogram pressure-input
      NP=$(echo $NP+1 | bc)
    fi
    sed '4d' input.in | sed '4i\mpid-pressure.in' | sed '1s/.*/1/' | sed "2s/.*/$NP/" > R$A-$B/pressure/input.in
    if [[ ! -f R$A-$B/pressure/CALC_ALREADY_STARTED ]]; then
      touch R$A-$B/pressure/CALC_ALREADY_STARTED
      cp -r scf_dir R$A-$B/pressure/
    else
      cd R$A-$B/pressure/
        mainprogram 2
      cd ../../
    fi
    for ((kk=1; kk<$NP; ++kk)); do
         
        if [ $dft == 'vasp' ] || [ $dft == 'VASP' ] ; then
             P=$(grep "v$kk\ " pressure.in | awk '{print $2}')
             if [[ ! -d R$A-$B/pressure/R$A-$P-$B ]] ; then
               mv R$A-$P-$B R$A-$B/pressure/
             fi
             cp run-vasp.sh R$A-$B/pressure/R$A-$P-$B/relax/run.sh
             cd R$A-$B/pressure/R$A-$P-$B/relax/
               if [[ ! -f NSW_0_DETECTED ]]; then
                   if [[ -f ../../../../CALC_VISIBLE_WITH_ID ]]; then 
                     mv run.sh $A-$kk.sh
                     sbatch $A-$kk.sh
                   elif [[ -f ../../../../CALC_VISIBLE_WITH_NAME ]]; then 
                     mv run.sh $B-$kk.sh
                     sbatch $B-$kk.sh
                   elif [[ -f ../../../../CALC_VISIBLE_WITH_ID-NAME ]]; then 
                     mv run.sh $A-$B-$kk.sh
                     sbatch $A-$B-$kk.sh
                   else
                     mv run.sh run-$kk.sh
                     sbatch run-$kk.sh
                   fi
               else
                  echo "Already NSW = 0 found"
               fi
             cd ../../../../
        else
             P=$(grep "v$kk\ " pressure.in | awk '{print $2}')
            if [[ -d R$A-$B ]]; then
              if [[ ! -d R$A-$B/pressure/R$A-$P-$B ]] ; then
                  echo " making R$A-$P-$B directory "
                  mkdir R$A-$B/pressure/R$A-$P-$B
              fi
              if [[ ! -d R$A-$B/pressure/R$A-$P-$B/relax ]] ; then
                  echo " making R$A-$P-$B/relax directory "
                  mkdir R$A-$B/pressure/R$A-$P-$B/relax
              fi
              if [[ -f R$A-$B/pressure/R$A-$P-$B/relax/scf.out ]]; then
                errorcheck=$(grep Error R$A-$B/pressure/R$A-$P-$B/relax/scf.out | wc -l)
                if [[ $errorcheck -gt 0 ]]; then
                   rm -r R$A-$B/pressure
                fi
              fi
              if [[ ! -f R$A-$B/pressure/R$A-$P-$B/relax/scf.in ]]; then
                cp scf_dir/scf-$A-$P.in R$A-$B/pressure/R$A-$P-$B/relax/scf.in
              fi
##    ##############
##     SUBMIT JOB ##
##    ##############
              echo " submitting jobs in R$A-$B/pressure/R$A-$P-$B/relax "
              cp run-scf.sh R$A-$B/pressure/R$A-$P-$B/relax/
              cd R$A-$B/pressure/R$A-$P-$B/relax/
                if [[ -f scf.out ]]; then
                 niter=$(grep ! scf.out | wc -l)
                else
                 niter=$(echo 100 | bc)
                fi
                if [[ $niter -lt 3 ]]; then
                  echo "Structure already relaxed"
                else
                  if [[ -f ../../../../CALC_VISIBLE_WITH_ID ]]; then 
                    mv run-scf.sh $A-$kk.sh
                    sbatch $A-$kk.sh
                  elif [[ -f ../../../../CALC_VISIBLE_WITH_NAME ]]; then 
                    mv run-scf.sh $B-$kk.sh
                    sbatch $B-$kk.sh
                  elif [[ -f ../../../../CALC_VISIBLE_WITH_ID-NAME ]]; then 
                    mv run-scf.sh $A-$B-$kk.sh
                    sbatch $A-$B-$kk.sh
                  else
                    sbatch run-scf.sh
                  fi
                    sleep $SLEEP
                fi
              cd ../../../../
            else
                continue
            fi
        fi    
    done
done
echo "all done"
