#! /bin/bash
# Writen by Niraj K. Nepal, Ph.D.
# Script to run first relaxation
# Runs for 'mainprogram 1'
source jobscript.sh

echo "---------------------------------------------------------------------------------------------------------------"
echo "Submitting crystal structure relaxation"
echo "---------------------------------------------------------------------------------------------------------------"
file=$(find * -name $3 | tail -n 1)
dft=$(grep "DFT" input.in | awk '{ print $3 }')
for ((ii=$1; ii<$2; ++ii)); do
  A=$(grep "v$ii\ " $file | awk '{print $2}')
  B=$(grep "v$ii\ " $file | awk '{print $3}')
  echo "$A $B"
  if [ $dft == 'vasp' ] || [ $dft == 'VASP' ]; then
    if [[ -d R$A-$B ]]; then
      if [[ -f vdw_kernel.bindat ]] && [[ ! -f R$A-$B/relax/vdw_kernel.bindat ]]; then
        cp vdw_kernel.bindat R$A-$B/relax/vdw_kernel.bindat
      fi
      cp run-vasp.sh R$A-$B/relax/run.sh
      cd R$A-$B/relax/
       vasprun "$A" "$B"
       sleep $SLEEP
      cd ../../
    fi


  else 
    if [[ ! -f scf_dir/scf-$A.in ]]; then
      qe_input.py $A
    fi
    echo "$A $B"
    if [[ ! -d R$A-$B ]] ; then
      echo " making R$A-$B directory "
      mkdir R$A-$B
    fi
    if [[ ! -d R$A-$B/relax ]] ; then
      echo " making R$A-$B/relax directory "
      mkdir R$A-$B/relax
    fi

    if [[ -d R$A-$B ]] ; then
      cp scf_dir/scf-$A.in R$A-$B/relax/temp.in
      sed '/pseudo_dir/d' R$A-$B/relax/temp.in > R$A-$B/relax/temp1.in
      sed "/calculation = 'vc-relax',/a pseudo_dir = '../../pp/'," R$A-$B/relax/temp1.in > R$A-$B/relax/scf.in
      rm R$A-$B/relax/temp*
      cp run-scf.sh R$A-$B/relax/
    fi
##  ##############
##   SUBMIT JOB ##
##  ##############
    echo " submitting jobs in R$A-$B/relax "
  cd R$A-$B/relax
     qerun "$A" "$B" "scf"
     sleep $SLEEP
  cd ../../
  fi
done
echo "all done"
