#!/usr/bin/env python
"""Generate ``docs/command.rst`` from :mod:`htesp.help_text`.

``docs/command.rst`` was a hand-transcribed copy of what ``mainprogram
basicinfo`` prints, and it had drifted: it omitted five commands the code
prints, named ``econv_vasp.csv`` where the code writes ``econv.csv``, and
misspelled the ``wanniertools_input`` config key.  Generating it from the same
constants the program prints makes that class of drift impossible.

    python tools/gen_command_rst.py [--check]

``--check`` exits 1 when the file on disk is out of date, for CI.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from htesp.help_text import HELP, PROCESS_SUMMARY, SUMMARY   # noqa: E402

TARGET = ROOT / "docs" / "command.rst"

HEADER = """.. _command-label:

Command reference
=================

.. warning::

   This page is generated by ``tools/gen_command_rst.py`` from
   ``htesp/help_text.py``, which is also what ``mainprogram`` prints.
   Edit the help text, not this file.

Every command is run as ``mainprogram <command>`` from the project directory
(the one holding ``input.in``).  ``mainprogram --list`` prints the same two
tables, and ``mainprogram --help`` prints the usage.

Global options
--------------

These may be added to any command:

``--workers N``
    Size of the per-material process pool.  Default ``min(cpu_count, 8)``;
    ``1`` disables multiprocessing.  ``$HTESP_WORKERS`` sets the default.

``--dry-run``
    Build every input file but never call the scheduler.  Nothing is submitted
    and nothing is deleted, so this is the safe way to check a campaign.

``--root DIR``
    Run against ``DIR`` instead of the working directory.

``--config FILE``
    Use ``FILE`` instead of searching for ``config.json``.  Equivalent to
    ``$HTESP_CONFIG``.

``--init-header CODE``
    Only with ``jobscript``: write a starting ``batch.header`` for that code,
    filled in from what SLURM and Lmod report on this machine.  ``CODE`` is
    ``vasp`` or any spelling of Quantum ESPRESSO (``qe``, ``QE``,
    ``QuantumEspresso``, ``quantum-espresso``).  Existing headers are kept
    unless ``--force`` is given.

``--force``
    Overwrite a file the command would otherwise refuse to replace.

``-v`` / ``--verbose``
    Debug logging.

Exit status is ``0`` on success, ``1`` when one or more materials failed,
``2`` for a bad command or a malformed ``input.in``, and ``130`` on Ctrl-C.
A stage in which every material failed now exits non-zero; in HTESP 1.x it
exited ``0`` because the bash layer discarded every exit code.

Numbered processes
------------------

.. list-table::
   :header-rows: 1
   :widths: 8 92

   * - Process
     - What it does
"""


def rows(mapping: dict[str, str]) -> str:
    out = []
    for key, text in sorted(mapping.items(),
                            key=lambda kv: (int(kv[0]) if kv[0].isdigit() else 0, kv[0])):
        out.append(f"   * - ``{key}``\n     - {text}\n")
    return "".join(out)


NAMED_HEADER = """
Named commands
--------------

.. list-table::
   :header-rows: 1
   :widths: 25 75

   * - Command
     - What it does
"""


def named_rows() -> str:
    return "".join(f"   * - ``{name}``\n     - {text}\n"
                   for name, text in sorted(SUMMARY.items()))


BLOCK_TITLES = {
    "basicinfo": "mainprogram basicinfo",
    "process-info": "mainprogram process-info",
    "epw-info": "mainprogram epw-info",
    "wt-info": "mainprogram wt-info",
}


def blocks() -> str:
    parts = ["\nThe built-in help blocks\n------------------------\n"]
    for name, title in BLOCK_TITLES.items():
        parts.append(f"\n{title}\n{'^' * len(title)}\n\n.. code-block:: text\n\n")
        parts.append("".join(f"   {line}\n" for line in HELP[name].splitlines()))
    return "".join(parts)


def render() -> str:
    return HEADER + rows(PROCESS_SUMMARY) + NAMED_HEADER + named_rows() + blocks()


def main(argv: list[str] | None = None) -> int:
    argv = list(argv if argv is not None else sys.argv[1:])
    text = render()
    if "--check" in argv:
        current = TARGET.read_text() if TARGET.is_file() else ""
        if current != text:
            print(f"{TARGET} is out of date; run python tools/gen_command_rst.py")
            return 1
        print(f"{TARGET} is up to date")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text)
    print(f"wrote {TARGET} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
