name: Publish Documentation

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Update to the latest version compatible with Node.js 20
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r docs/requirement.txt

      - name: Build documentation
        run: |
          make -C docs clean html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/_build/html

